package com.example.entity;

import com.example.entity.TblDirectExample;
import com.example.entity.TblDirectKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TblDirectDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_direct
     *
     * @mbg.generated Fri Mar 24 17:38:11 JST 2017
     */
    long countByExample(TblDirectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_direct
     *
     * @mbg.generated Fri Mar 24 17:38:11 JST 2017
     */
    int deleteByExample(TblDirectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_direct
     *
     * @mbg.generated Fri Mar 24 17:38:11 JST 2017
     */
    int deleteByPrimaryKey(TblDirectKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_direct
     *
     * @mbg.generated Fri Mar 24 17:38:11 JST 2017
     */
    int insert(TblDirectKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_direct
     *
     * @mbg.generated Fri Mar 24 17:38:11 JST 2017
     */
    int insertSelective(TblDirectKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_direct
     *
     * @mbg.generated Fri Mar 24 17:38:11 JST 2017
     */
    List<TblDirectKey> selectByExample(TblDirectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_direct
     *
     * @mbg.generated Fri Mar 24 17:38:11 JST 2017
     */
    int updateByExampleSelective(@Param("record") TblDirectKey record, @Param("example") TblDirectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_direct
     *
     * @mbg.generated Fri Mar 24 17:38:11 JST 2017
     */
    int updateByExample(@Param("record") TblDirectKey record, @Param("example") TblDirectExample example);
}