package com.example.entity;

import com.example.entity.TblExpression2;
import com.example.entity.TblExpression2Example;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TblExpression2Dao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_expression2
     *
     * @mbg.generated Fri Mar 24 17:38:11 JST 2017
     */
    long countByExample(TblExpression2Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_expression2
     *
     * @mbg.generated Fri Mar 24 17:38:11 JST 2017
     */
    int deleteByExample(TblExpression2Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_expression2
     *
     * @mbg.generated Fri Mar 24 17:38:11 JST 2017
     */
    int deleteByPrimaryKey(String expId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_expression2
     *
     * @mbg.generated Fri Mar 24 17:38:11 JST 2017
     */
    int insert(TblExpression2 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_expression2
     *
     * @mbg.generated Fri Mar 24 17:38:11 JST 2017
     */
    int insertSelective(TblExpression2 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_expression2
     *
     * @mbg.generated Fri Mar 24 17:38:11 JST 2017
     */
    List<TblExpression2> selectByExampleWithBLOBs(TblExpression2Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_expression2
     *
     * @mbg.generated Fri Mar 24 17:38:11 JST 2017
     */
    List<TblExpression2> selectByExample(TblExpression2Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_expression2
     *
     * @mbg.generated Fri Mar 24 17:38:11 JST 2017
     */
    TblExpression2 selectByPrimaryKey(String expId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_expression2
     *
     * @mbg.generated Fri Mar 24 17:38:11 JST 2017
     */
    int updateByExampleSelective(@Param("record") TblExpression2 record, @Param("example") TblExpression2Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_expression2
     *
     * @mbg.generated Fri Mar 24 17:38:11 JST 2017
     */
    int updateByExampleWithBLOBs(@Param("record") TblExpression2 record, @Param("example") TblExpression2Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_expression2
     *
     * @mbg.generated Fri Mar 24 17:38:11 JST 2017
     */
    int updateByExample(@Param("record") TblExpression2 record, @Param("example") TblExpression2Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_expression2
     *
     * @mbg.generated Fri Mar 24 17:38:11 JST 2017
     */
    int updateByPrimaryKeySelective(TblExpression2 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_expression2
     *
     * @mbg.generated Fri Mar 24 17:38:11 JST 2017
     */
    int updateByPrimaryKeyWithBLOBs(TblExpression2 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_expression2
     *
     * @mbg.generated Fri Mar 24 17:38:11 JST 2017
     */
    int updateByPrimaryKey(TblExpression2 record);
}