package com.example.entity;

import com.example.entity.TblExpression;
import com.example.entity.TblExpressionExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TblExpressionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_expression
     *
     * @mbg.generated Fri Mar 24 17:36:23 JST 2017
     */
    long countByExample(TblExpressionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_expression
     *
     * @mbg.generated Fri Mar 24 17:36:23 JST 2017
     */
    int deleteByExample(TblExpressionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_expression
     *
     * @mbg.generated Fri Mar 24 17:36:23 JST 2017
     */
    int deleteByPrimaryKey(String expId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_expression
     *
     * @mbg.generated Fri Mar 24 17:36:23 JST 2017
     */
    int insert(TblExpression record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_expression
     *
     * @mbg.generated Fri Mar 24 17:36:23 JST 2017
     */
    int insertSelective(TblExpression record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_expression
     *
     * @mbg.generated Fri Mar 24 17:36:23 JST 2017
     */
    List<TblExpression> selectByExampleWithBLOBs(TblExpressionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_expression
     *
     * @mbg.generated Fri Mar 24 17:36:23 JST 2017
     */
    List<TblExpression> selectByExample(TblExpressionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_expression
     *
     * @mbg.generated Fri Mar 24 17:36:23 JST 2017
     */
    TblExpression selectByPrimaryKey(String expId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_expression
     *
     * @mbg.generated Fri Mar 24 17:36:23 JST 2017
     */
    int updateByExampleSelective(@Param("record") TblExpression record, @Param("example") TblExpressionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_expression
     *
     * @mbg.generated Fri Mar 24 17:36:23 JST 2017
     */
    int updateByExampleWithBLOBs(@Param("record") TblExpression record, @Param("example") TblExpressionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_expression
     *
     * @mbg.generated Fri Mar 24 17:36:23 JST 2017
     */
    int updateByExample(@Param("record") TblExpression record, @Param("example") TblExpressionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_expression
     *
     * @mbg.generated Fri Mar 24 17:36:23 JST 2017
     */
    int updateByPrimaryKeySelective(TblExpression record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_expression
     *
     * @mbg.generated Fri Mar 24 17:36:23 JST 2017
     */
    int updateByPrimaryKeyWithBLOBs(TblExpression record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_expression
     *
     * @mbg.generated Fri Mar 24 17:36:23 JST 2017
     */
    int updateByPrimaryKey(TblExpression record);
}