package com.example.entity;

import com.example.entity.TblRole;
import com.example.entity.TblRoleExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TblRoleDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_role
     *
     * @mbg.generated Fri Mar 24 17:38:11 JST 2017
     */
    long countByExample(TblRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_role
     *
     * @mbg.generated Fri Mar 24 17:38:11 JST 2017
     */
    int deleteByExample(TblRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_role
     *
     * @mbg.generated Fri Mar 24 17:38:11 JST 2017
     */
    int deleteByPrimaryKey(String roleId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_role
     *
     * @mbg.generated Fri Mar 24 17:38:11 JST 2017
     */
    int insert(TblRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_role
     *
     * @mbg.generated Fri Mar 24 17:38:11 JST 2017
     */
    int insertSelective(TblRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_role
     *
     * @mbg.generated Fri Mar 24 17:38:11 JST 2017
     */
    List<TblRole> selectByExample(TblRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_role
     *
     * @mbg.generated Fri Mar 24 17:38:11 JST 2017
     */
    TblRole selectByPrimaryKey(String roleId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_role
     *
     * @mbg.generated Fri Mar 24 17:38:11 JST 2017
     */
    int updateByExampleSelective(@Param("record") TblRole record, @Param("example") TblRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_role
     *
     * @mbg.generated Fri Mar 24 17:38:11 JST 2017
     */
    int updateByExample(@Param("record") TblRole record, @Param("example") TblRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_role
     *
     * @mbg.generated Fri Mar 24 17:38:11 JST 2017
     */
    int updateByPrimaryKeySelective(TblRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_role
     *
     * @mbg.generated Fri Mar 24 17:38:11 JST 2017
     */
    int updateByPrimaryKey(TblRole record);
}