package com.example.entity;

import com.example.entity.TblText;
import com.example.entity.TblTextExample;
import com.example.entity.TblTextKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TblTextMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_text
     *
     * @mbg.generated Fri Mar 24 17:36:23 JST 2017
     */
    long countByExample(TblTextExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_text
     *
     * @mbg.generated Fri Mar 24 17:36:23 JST 2017
     */
    int deleteByExample(TblTextExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_text
     *
     * @mbg.generated Fri Mar 24 17:36:23 JST 2017
     */
    int deleteByPrimaryKey(TblTextKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_text
     *
     * @mbg.generated Fri Mar 24 17:36:23 JST 2017
     */
    int insert(TblText record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_text
     *
     * @mbg.generated Fri Mar 24 17:36:23 JST 2017
     */
    int insertSelective(TblText record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_text
     *
     * @mbg.generated Fri Mar 24 17:36:23 JST 2017
     */
    List<TblText> selectByExampleWithBLOBs(TblTextExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_text
     *
     * @mbg.generated Fri Mar 24 17:36:23 JST 2017
     */
    List<TblText> selectByExample(TblTextExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_text
     *
     * @mbg.generated Fri Mar 24 17:36:23 JST 2017
     */
    TblText selectByPrimaryKey(TblTextKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_text
     *
     * @mbg.generated Fri Mar 24 17:36:23 JST 2017
     */
    int updateByExampleSelective(@Param("record") TblText record, @Param("example") TblTextExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_text
     *
     * @mbg.generated Fri Mar 24 17:36:23 JST 2017
     */
    int updateByExampleWithBLOBs(@Param("record") TblText record, @Param("example") TblTextExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_text
     *
     * @mbg.generated Fri Mar 24 17:36:23 JST 2017
     */
    int updateByExample(@Param("record") TblText record, @Param("example") TblTextExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_text
     *
     * @mbg.generated Fri Mar 24 17:36:23 JST 2017
     */
    int updateByPrimaryKeySelective(TblText record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_text
     *
     * @mbg.generated Fri Mar 24 17:36:23 JST 2017
     */
    int updateByPrimaryKeyWithBLOBs(TblText record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_text
     *
     * @mbg.generated Fri Mar 24 17:36:23 JST 2017
     */
    int updateByPrimaryKey(TblText record);
}