package com.example.entity;

import com.example.entity.TblWordKind;
import com.example.entity.TblWordKindExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TblWordKindMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_word_kind
     *
     * @mbg.generated Fri Mar 24 17:36:23 JST 2017
     */
    long countByExample(TblWordKindExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_word_kind
     *
     * @mbg.generated Fri Mar 24 17:36:23 JST 2017
     */
    int deleteByExample(TblWordKindExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_word_kind
     *
     * @mbg.generated Fri Mar 24 17:36:23 JST 2017
     */
    int deleteByPrimaryKey(String wordKindId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_word_kind
     *
     * @mbg.generated Fri Mar 24 17:36:23 JST 2017
     */
    int insert(TblWordKind record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_word_kind
     *
     * @mbg.generated Fri Mar 24 17:36:23 JST 2017
     */
    int insertSelective(TblWordKind record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_word_kind
     *
     * @mbg.generated Fri Mar 24 17:36:23 JST 2017
     */
    List<TblWordKind> selectByExample(TblWordKindExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_word_kind
     *
     * @mbg.generated Fri Mar 24 17:36:23 JST 2017
     */
    TblWordKind selectByPrimaryKey(String wordKindId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_word_kind
     *
     * @mbg.generated Fri Mar 24 17:36:23 JST 2017
     */
    int updateByExampleSelective(@Param("record") TblWordKind record, @Param("example") TblWordKindExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_word_kind
     *
     * @mbg.generated Fri Mar 24 17:36:23 JST 2017
     */
    int updateByExample(@Param("record") TblWordKind record, @Param("example") TblWordKindExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_word_kind
     *
     * @mbg.generated Fri Mar 24 17:36:23 JST 2017
     */
    int updateByPrimaryKeySelective(TblWordKind record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_word_kind
     *
     * @mbg.generated Fri Mar 24 17:36:23 JST 2017
     */
    int updateByPrimaryKey(TblWordKind record);
}